Isv 1386
redhat-openshift-ecosystem/operator-pipelines pull request #252
Opened 2022-02-14 10:45 UTC by mantomas

WiP

2022-02-14 11:46 UTC, Allda requested changes

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +from ast import arg
This import is not needed.

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +        help="When a tag is specified, and `REPLACE` is `true`, look for a comment with a matching tag and replace it with the new comment.",
Please update the description based on python arguments names.

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +    api_url = "{base}/repos/{package}/issues/{id}".format(
Please use f-strings instead of `format()`. https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +    commentParamValue = comment_or_file
Please use snake_case variable names instead of CamelCase. https://www.theserverside.com/answer/Camel-case-vs-snake-case-Whats-the-difference

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +        commentParamValue = open(commentParamValue, "r").read()
It is recommended to use `with open(...)` https://www.programiz.com/python-programming/file-operation

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +        commentParamValue += "<!-- {tag} -->".format(tag=commen_tag)
f-strings

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +            print("REPLACE requested but no COMMENT_TAG specified")
Instead of print() use `LOGGER.{info/debug/warning/error}`

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +            print("REPLACE requested but no COMMENT_TAG specified")
Also, the message makes sense in the old code. Please update a message to reflect actual script arguments.

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +        r = conn.request(
Please use `github` module to communicate with the Github API.

2022-02-14 11:46 UTC, Allda commented on operator-pipeline-images/operatorcert/entrypoints/github_add_comment.py
> +    r = conn.request(
Same here.

2022-02-15 12:57 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-15 13:04 UTC, Allda commented on operator-pipeline-images/operatorcert/github.py
> +            f"Github POST query failed with {url} - {resp.status_code} - {resp.text}"
Use PATCH in the message.

2022-02-16 07:39 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-16 07:49 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-16 07:52 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-16 07:53 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-16 08:12 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-16 08:25 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-16 08:29 UTC, mantomas commented
Test comment.<!-- test_tag_2 -->

2022-02-16 12:59 UTC, Allda commented on operator-pipeline-images/tests/entrypoints/test_github_add_comment.py
> +def test_github_add_comment_POST(mock_post: MagicMock) -> None:
Please keep the function name lowercase. Also, update other function names in this file.

2022-02-16 13:40 UTC, Allda commented on ansible/roles/operator-pipeline/templates/openshift/tasks/github-add-comment.yml
> +        echo $params.COMMENT_OR_FILE > comment_file
Since you always accept just a comment string can you rename the parameter to just `COMMENT` and also remove the workspace?

2022-02-17 09:56 UTC, Allda commented on ansible/roles/operator-pipeline/templates/openshift/tasks/github-add-comment.yml
> +        echo $params.COMMENT_OR_FILE > comment_file
Yes, everywhere.

2022-02-23 15:03 UTC, Allda approved these changes

2022-02-23 15:18 UTC, merged