Timeout release 1.5hr
redhat-openshift-ecosystem/operator-pipelines pull request #256
Opened 2022-02-18 05:35 UTC by Mitulsharma123

timeout added as 1.5 hours for release pipeline

2022-02-21 09:22 UTC, Allda commented
@Mitulsharma123 I can help you with the rebase but first can you provide more details on this change? The current timeout is set to 2 hours. Is it really intentional to decrease to 1.5 hours?

2022-02-21 13:37 UTC, Mitulsharma123 commented
@Allda followed what you've commented in https://github.com/redhat-openshift-ecosystem/operator-pipelines/pull/254#issuecomment-1043216430

2022-02-21 20:26 UTC, amisstea requested changes

2022-02-21 20:26 UTC, amisstea commented on ansible/roles/operator-pipeline/tasks/webhook-hosted-pipeline-trigger.yml
> +                  timeout: "1.5h"
This is changing the overall timeout of the hosted pipeline which should stay at `2h`. Please define the timeout in the release pipeline trigger instead.

2022-02-21 20:26 UTC, amisstea commented on README.md
> +**To run any of the pipelines for the first time, multiple cluster resources have to be created.**
You have a few merged git conflicts scattered around. Please rebase/fix your branch to remove the dupe commit.

2022-02-22 07:33 UTC, Mitulsharma123 commented
@amisstea I've removed the conflict part, let me know if there is a still issue ? let me know, where can i ping you outside github.

2022-02-22 14:06 UTC, amisstea commented
@Mitulsharma123 something didn't go according to plan with your rebasing. There are even more commits now and the relevant changes were omitted. Please reach out on gchat if you need assistance.

2022-02-25 16:22 UTC, amisstea commented
Dupe of #266. Closing.

2022-02-25 16:22 UTC, closed without merging