Custom k8s defaults
redhat-openshift-ecosystem/operator-pipelines pull request #357
Opened 2022-10-11 17:57 UTC by J0zi

Custom k8s defaults triggered by a flag, original defaults left intact

2022-10-12 06:50 UTC, Allda requested changes
The CI pipeline can't have variables defined by ansible because we can't force partners to always use ansible. The pipeline is directly used from the repository.

2022-10-13 07:36 UTC, J0zi commented
OK, changes reverted. Adding just DNS related updates.

2022-10-13 11:55 UTC, Allda approved these changes

2022-10-13 12:16 UTC, mvalarh approved these changes

2022-10-13 12:16 UTC, merged