[ISV-4837] Incorrect behaviour of the operator pipelines when a PR affects only ci.yaml.
redhat-openshift-ecosystem/operator-pipelines pull request #667
Opened 2024-06-05 23:35 UTC by haripate

2024-06-25 04:45 UTC, haripate commented
> @haripate What is going on with this PR? Is there anything missing or do you need help with the validation and failed linters?

@Allda I am trying to figure out the reason for the Safety failure test.

2024-06-25 09:00 UTC, mporrato requested changes

2024-06-25 11:44 UTC, Allda commented
> > @haripate What is going on with this PR? Is there anything missing or do you need help with the validation and failed linters?
> 
> @Allda I am trying to figure out the reason for the Safety failure test.

The Safety issue is already resolved in main branch. Please rebase your PR

2024-06-27 08:22 UTC, haripate commented on ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-release-pipeline.yml
> +          values: [""]
I have added the same `when` condition in `upload-pipeline-logs` task as well so it will skip this task as well.

2024-06-27 08:22 UTC, haripate commented on ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-hosted-pipeline.yml
> +        - *bundleAdded
Updated.

2024-06-27 13:40 UTC, mporrato requested changes

2024-06-27 13:40 UTC, mporrato commented on ansible/roles/operator-pipeline/templates/openshift/tasks/cert-project-check.yml
>          CI_FILE_PATH="$PKG_PATH/ci.yaml"
It does not matter because the workingDir of the task is set to the `source` workspace so the relative path should be enough.

2024-06-27 13:51 UTC, mporrato approved these changes

2024-06-27 14:00 UTC, merged